dist: xenial
language: python
python:
   - "3.6"
jobs:
  include:
     - stage: test
       script:
         - python main.py
    - stage: deploy
       script:
         - python main.py
branches:
  only:
  - master