dist: xenial
language: python
stages:
  - test
  - deploy
python:
   - "3.6"
jobs:
  include:
    - stage: "test"
      script:
          - python -V
      only:
        branches:
          - master
    - stage: "deploy"
      script:
          - python main.py
      only:
          branches:
            - master