dist: xenial
language: python
stages:
  - test
  - deploy
python:
   - "3.6"
services:
  - redis
before_script:
  - redis-cli SET a b
  - redis-cli GET a
# jobs:
#   include:
#     - stage: "test"
#       script:
#           - python -V
#       if: branch = master
#     - stage: "deploy"
#       script:
#           - python main.py
#       if: branch = master
