dist: xenial
language: python
stages:
  - test
  - deploy
python:
   - "3.6"
jobs:
  include:
     - stage: test
       script:
         - python main.py
       if: branch = master
    - stage: deploy
       script:
         - python main.py
       if: branch = master